### ISSUE TITLE
Create a data-grid Web component

### ISSUE THREAD

**Issue by jswale** [amalto/platform6-ui-components#128]
**Features**

- [x] Filter (column, cell)
- [x] Order
- [x] Move column
- [x] Remove column
- [x] Change alignment (left/middle/right)
- [ ] Change column color
- [x] Change width
- [x] Editable cells
- [x] User preferences
- [ ] Pagination
- [ ] Limit

**UI**
![Screenshot 2020-06-11 at 14 49 41](https://user-images.githubusercontent.com/6729188/84387262-05be9480-abf3-11ea-9ee1-e856669a30ec.png)

**Comment by vuongc** [comment]
**Features**

- [ ] Filter (column, cell)
- [ ] Order
- [ ] Move column
- [ ] Remove column
- [ ] Change alignment (left/middle/right)
- [ ] Change column color
- [ ] Change width
- [ ] Editable cells
- [ ] User preferences
- [ ] Pagination
- [ ] Limit

**UI**
![Screenshot 2020-06-11 at 14 49 41](https://user-images.githubusercontent.com/6729188/84387262-05be9480-abf3-11ea-9ee1-e856669a30ec.png)
