### ISSUE TITLE
Default column is not correctly filled

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#13]
The default column doesn't present the default values. `Required` is no a default value, it should be in the description cell.
For example, in the example below, the default values are not set: `btnClass` -> "" ...

![screen shot 2018-03-29 at 14 34 36](https://user-images.githubusercontent.com/9531852/38089073-7dd7949a-335e-11e8-8f0a-77b26a32e18a.png)

**Comment by roxanemace** [comment]
![screen shot 2018-03-29 at 15 27 21](https://user-images.githubusercontent.com/9531852/38091390-b641e78e-3365-11e8-9ea2-a680c4d2873a.png)

Same here!

**Comment by vuongc** [comment]
Display a red start near the props name if required and don't display `Required` on `Default`.
Won't put empty string/undefined as default value.
