### ISSUE TITLE
Props "locale" is not well explained #ButtonsBar

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#14]
The description of the props `locale` is not sufficient. You are saying that the props `locale` is a locale, you are not explaining what it's used for, what is the default value and what are the available values.

Moreover, you should add a link to the method which gets the locale from the browser `webStorage.locale` and how to format it

`
export function formatLocale (locale: string): string {
	return locale.substring(0, locale.indexOf('-')).toUpperCase()
}
`

**Comment by vuongc** [comment]
`formatLocale` is already implemented in the `helpers` under the `getI18nLabel` name.

**Comment by roxanemace** [comment]
1) You should add a link to `WebStorage` (eg: ActionButton: `Accessible via WebStorage`)
2) You should give ALL the available locale values (`fr-FR`, ...) or add a link to redirect toward the list.

**Comment by vuongc** [comment]
I said we should use `getI18nLabel` intead of `formatLocale` but it should be `dateByLocalToString` instead.
