### ISSUE TITLE
Refactor switch web component

### ISSUE THREAD

**Issue by jswale** [amalto/platform6-ui-components#163]
Get inspired from https://github.com/Gomah/bulmil/tree/master/packages/bulmil/src/core/form/switch

Issue #142

**Comment by vuongc** [comment]
![Screenshot 2020-06-08 at 09 27 47](https://user-images.githubusercontent.com/6729188/84003442-566f8c80-a96a-11ea-9795-d485d8339e67.png)

I don't think we need to add a `class`, `color`, `isOutline`, `isRounded`, `isThin` and a `size` properties to the component. WDYT @vincentv @jswale ?

**Comment by vuongc** [comment]
aas we discussed only the switch color will be changed to `info`
