### ISSUE TITLE
Add for each component a link to the npm package

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#25]
You need to add a link to the npm package for each component:

For example for the Helpers, add https://www.npmjs.com/package/%40amalto%2Fhelpers.

Here is the Atlassian Component kit: 
![screen shot 2018-03-30 at 17 11 40](https://user-images.githubusercontent.com/9531852/38142677-901c9788-343d-11e8-8ee1-764aaff43d1f.png)

**Comment by vuongc** [comment]
Refer to issue #31 which regroups all the issues concerning the description section of each component.
