### ISSUE TITLE
Display the last version of each component

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#26]
You need to display somewhere the version of the component which you document.

Add the tag `latest`, if it's the latest version.
![screen shot 2018-03-30 at 17 14 18](https://user-images.githubusercontent.com/9531852/38142732-cde4e5ca-343d-11e8-8f18-d15079cced80.png)

**Comment by vuongc** [comment]
Refer to issue #31 which regroups all the issues concerning the description section of each component.
