### ISSUE TITLE
Create a new method to handle a service's item name duplication

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#29]
The current signature of the method is: 
```typescript
function handleDuplicateNameFromArray( name: string, container: string[]): string;
```

I think it would be better if the method takes in argument the item's id and the current facade list. The method should be more specific to Platform 6 services.

I suggest the following method (of course it's just a suggestion, you may choose a different method's name or logic).

```typescript
/**
 * Increment an item's name
 *
 * @param {ServiceItemFacades} facades
 * @param {Interfaces.Id} id
 * @returns {string}
 */
export function incrementName (facades: ServiceItemFacades, id: Interfaces.Id): string {
	const { name } = id
	let index = 1

	const facadesWithSameAppKey = facades.filter(f => f.appKey === id.appKey)

	if (facadesWithSameAppKey.length === 0) return name

	while (!facadesWithSameAppKey.every(f => f.name !== `${name}_${index}`)) index++

	return `${name}_${index}`
}
```

with the following interfaces

```typescript
    interface Id {
        name: string
        appKey: string
    }
```

```typescript
	interface ServiceItemFacade extends Id {
		description: string
		calculatedContentMode: string
		appInfo?: string
		lastModifiedBy?: string
		lastModifiedDate?: number
		revisionId?: string
	}
```

**Comment by vuongc** [comment]
In our case it is indeed better to pass and `Id` and an array of `ServiceItemFacade`, but this mean it will restrict this method to format only `ServiceItemFacade`.

In my case I use it when I want to duplicate a resource name which does not contain an `appKey` nor it is a `ServiceItemFacade`.

For the purpose you want you just have to pass an array of name where the `appKey` is the same as the `ServiceItemFacade` you want to duplicate.

**Comment by vuongc** [comment]
We can also add your implementation under another name.

**Comment by roxanemace** [comment]
I've forgotten you use this method for a script's resource.

So let's keep your method and create a second one which uses `handleDuplicateNameFromArray`.

What do you think of it?

**Comment by vuongc** [comment]
Agreed

**Comment by vuongc** [comment]
The method has been added under the `handleDuplicateServiceItemName` name.
