### ISSUE TITLE
Clean the wordings

### ISSUE THREAD

**Issue by vuongc** [amalto/platform6-ui-components#32]
Should replace all the `keys` to `camelCase` and replace it whenever you find it.

You should look into the services and the core ui.

**Comment by roxanemace** [comment]
At the start of the wordings, you add a line between each wording. But it's not the case in the middle of the section.

<img width="355" alt="screen shot 2018-04-18 at 11 15 00" src="https://user-images.githubusercontent.com/9531852/38923054-0597749a-42fa-11e8-9d60-7656136882be.png">

**Comment by roxanemace** [comment]
- [ ] Why is there wordings for bundled resources?
