### ISSUE TITLE
Add the command line to install the package

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#5]
Display for each component the command line to install the package (under the title for example).

![screen shot 2018-03-16 at 17 05 37](https://user-images.githubusercontent.com/9531852/37531402-597a7756-293c-11e8-8b84-5cd5280dd693.png)

**Comment by vuongc** [comment]
Replace import line by install command line

**Comment by roxanemace** [comment]
You shouldn't have removed the line "import Tabs from "@amalto/Tabs". You can add it to the example.
`
import ActionButton from '@amalto/action-button'

<ActionButton clickAction={e => window.alert('click on button')}
    iconClass='fas fa-info'
    colorClass='' // Set to empty string to prevent conflict with `btn-info` class
    btnClass='btn btn-trans btn-info'
    disabled={false}
    tooltipText='Info button'
/>`

**Comment by vuongc** [comment]
Related to #31
