### ISSUE TITLE
Error when using PdfViewer in a service UI

### ISSUE THREAD

**Issue by fmontaigne** [amalto/platform6-ui-components#59]
Error: `Failed loading PDF Error: No PDFJS.workerSrc specified`

Using the portal embedded one works (via platform6.PdfViewer)

**Comment by vuongc** [comment]
Fixed by loading initializing  `PDFJS.workerSrc = require( 'pdfjs-dist/build/pdf.worker.entry.js' )` initializing the pdfjs library.
