### ISSUE TITLE
Fix spelling mistakes

### ISSUE THREAD

**Issue by roxanemace** [amalto/platform6-ui-components#6]
I'll add all the spelling mistakes I saw in the documentation

- [x] Add a link to Font Awesome each time you write.
- [x] It's not `FontAwesome` but `Font Awesome`.
- [x] `This documentation regroup all the component available for you to develop your own service on Platform6.` => `regroups`, `Platform 6`
- [x] `Edit the code and see the exemple being edited for each component.` => `example`
- [x] Add a dot at the end of sentence: `All the components provided by Platform 6`
- [x] `Small button with an icon instead of text.` => `A small ...`
- [x] `Set the icon color class. Do not use if you don't need it, otherwise btnClass will have trouble handeling hover color.` => `Set the icon colour class. Do not use if you don't need it, otherwise, btnClass will have trouble handling hover colour.`
- [x] `Modal use to confirm a file upload.` => `used`
- [x] `Commons classes` => `Common classes`
- [x] `otherwise the class wont work.` => `otherwise the class won't work.`
- [x] `return the same object passed as param but with ASC ordered keys.` => `Return`
- [x] `return the same object passed as param but with DESC ordered keys.` => `Return`
- [x] `It uses an TreeNodeDataModel object` => `It uses a ...`
- [x] `ScopeValue interface is not editable and usable by user, it regroup the user's actions he is able to perform.` => `by the user`, `regroups`
- [x] "This component is not a stand alone component because his functionnalities uses actions from the core." -> "This component is not a stand-alone component because its functionalities use actions from the core."

**Comment by vuongc** [comment]
We have always used `color` and not `colour`, there is not meaning to change it now.

**Comment by roxanemace** [comment]
DatePicker
`There is a few customizations like a minimum and a maximum date range of date available.` -> `There are `
